Exposing RSA-PSS
hacl-star/hacl-star pull request #587
Opened 2022-08-10 16:32 UTC by Frosne

This PR aims in exposing the RSA-PSS functionality for Mozilla.

2022-08-10 16:36 UTC, msprotz requested changes
Please make sure your dist/ diff is clean, right now, I think the file Hacl_Hash_... is superfluous. Other than that, looks good.

2022-08-10 16:36 UTC, msprotz commented on Makefile
> +dist/mozilla/Makefile.basic: BIGNUM_BUNDLE = -bundle Hacl.Bignum=Hacl.Bignum,Hacl.Bignum.* -bundle Hacl.Bignum256_32,Hacl.Bignum4096_32,Hacl.Bignum256,Hacl.Bignum4096,Hacl.Bignum32,Hacl.Bignum64,Hacl
no need to repeat Hacl.Bignum on the right-hand side of the equals sign

2022-08-24 16:32 UTC, Frosne commented
I think Hacl_Hash* is expected, RSA PSS uses a hash function.

2022-08-24 17:21 UTC, msprotz commented
Then maybe append `[rename=Hacl_Hash]` to your HASH_BUNDLE so that the filename is more palatable?

2022-10-06 15:59 UTC, msprotz commented
- Please resolve conflicts
- Please refresh dist/mozilla -- right now I still see that very long filename in there.

```
git rm -rf dist/mozilla/*
make compile-mozilla
git add dist/mozilla
git commit -m "Refresh dist/mozilla"
```

2022-10-18 15:34 UTC, msprotz commented
The build log contains errors about 

```
make[2]: *** [<builtin>: Hacl_Bignum256_32_Hacl_Bignum4096_32_Hacl_Bignum256_Hacl_Bignum4096_Hacl_Bignum32_Hacl_Bignum64_Hacl_GenericField32_Hacl_GenericField64_Hacl_Bignum_Hacl_Bignum.o] Error 1
```

so this still doesn't appear to be working. Let me try to suggest an alternative today.

2022-10-18 17:06 UTC, msprotz commented
New error:
```
internal/Hacl_Bignum.h:39:10: fatal error: lib_intrinsics.h: No such file or directory
   39 | #include "lib_intrinsics.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile.basic:53: Hacl_Chacha20Poly1305_256.d: No such file or directory
make[2]: *** [Makefile.basic:48: Hacl_RSAPSS.d] Error 1
```

2022-10-27 13:24 UTC, msprotz commented
Once we merge #649, we can address this very simply.

2022-11-01 12:16 UTC, closed without merging